export enum SElement {
  app = 'synthia-app',
  root = 'synthia-root',
  canvas = 'synthia-canvas',
  oscillator = 'synthia-oscillator',
  oscillatorSidebar = 'synthia-oscillator-sidebar',
  filter = 'synthia-filter',
  filterSidebar = 'synthia-filter-sidebar',
  waveform = 'synthia-waveform',
  frequencyResponse = 'synthia-frequency-response',
  circleMenu = 'synthia-circle-menu',
  button = 'synthia-button',
  slider = 'synthia-slider',
  expoSlider = 'synthia-expo-slider',
  footer = 'synthia-footer',
  sidebar = 'synthia-sidebar',
  toaster = 'synthia-toaster',
  delay = 'synthia-delay',
  reverb = 'synthia-reverb',
  reverbSidebar = 'synthia-reverb-sidebar',
}
