export enum SElement {
  app = 'synthia-app',
  root = 'synthia-root',
  canvas = 'synthia-canvas',
  wave = 'synthia-wave',
  waveSidebar = 'synthia-wave-sidebar',
  filter = 'synthia-filter',
  filterSidebar = 'synthia-filter-sidebar',
  waveform = 'synthia-waveform',
  frequencyResponse = 'synthia-frequency-response',
  circleMenu = 'synthia-circle-menu',
  button = 'synthia-button',
  slider = 'synthia-slider',
  expoSlider = 'synthia-expo-slider',
  footer = 'synthia-footer',
  sidebar = 'synthia-sidebar',
  toaster = 'synthia-toaster',
  delay = 'synthia-delay',
  delaySidebar = 'synthia-delay-sidebar',
  reverb = 'synthia-reverb',
  reverbSidebar = 'synthia-reverb-sidebar',
  pan = 'synthia-pan',
  panSidebar = 'synthia-pan-sidebar',
}
